### ISSUE TITLE
Instalación SDK

### ISSUE THREAD

**Issue by solmartinezp** [decidir/sdk-nodejs-v2#12]
Hola, en la sección de Instalación del README dice:
"Descargar la última versión del SDK desde el botón Download ZIP en (poner link). Se debe incluirse la carpeta del SDK dentro del proyecto"
y no incluyeron el link de descarga.

**Comment by mmansilla-prisma** [comment]
Buenos días @solmartinezp, esa sección del README hace referencia al botón code que se encuentra a mitad de altura, en el desplegable se dará la opción de descargarlo como zip, te dejo una captura

![image](https://user-images.githubusercontent.com/83774187/148977917-5acac84c-7782-4fe8-9dc7-1bb4077f80e7.png)

Sacando esto de lado, estamos mejorando la SDK y ajustando el README a las nuevas versiones, tratando de hacernos entender lo mejor posible.

Muchas gracias, saludos!
