### ISSUE TITLE
Bad Documented - Environments

### ISSUE THREAD

**Issue by pr0duc3r** [decidir/sdk-nodejs-v2#3]
Ambient variable was documented as:
`var ambient = "test";//valores posibles: "test" o "prod";`

on lib/sdk.js expects:
`        if (environment == 'developer') {
            endpoint = 'https://developers.decidir.com/api/v2'
        } else if (environment == 'production') {
            endpoint = 'https://live.decidir.com/api/v2'
        }`

**Comment by mmansilla-prisma** [comment]
Buenos días, mil disculpas @pr0duc3r ya fue corregida  documentación 

![image](https://user-images.githubusercontent.com/83774187/148977383-77e77bd7-19f9-429e-9fac-c59f5d3f4f09.png)

Saludos
